server:
  port: 9201

service-url:
  user-service: http://localhost:8201
  news-service: http://localhost:8301

spring:
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: ${service-url.user-service}/user
          predicates:
            - Path=/user/**
        - id: news_route
          uri: ${service-url.news-service}/news
          predicates:
            - Path=/news/**

logging:
  level:
    org.springframework.cloud.gateway: debug